name: anysend
description: AnySend Client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  async: ^2.11.0
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_timer_countdown: ^1.0.5
  flutter_webrtc: ^0.9.45
  http_interceptor: ^1.0.2
  intl: any
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  shared_storage: ^0.8.0
  wakelock_plus: ^1.1.3
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  msix: ^3.16.6

flutter:
  generate: true
  uses-material-design: true

import_sorter:
  comments: false

msix_config:
  msix_version: 1.0.2.0
  msstore_appId: 9NPKG5X6W2SZ
  display_name: ZeroBlue AnySend
  publisher_display_name: ZeroBlue
  identity_name: 45119ZeroBlue.ZeroBlueAnySend
  publisher: CN=BB79A522-16C1-4E37-9E0D-84749E370391
  store: true
  capabilities: runFullTrust, internetClient, internetClientServer
  languages: en, zh-cn
  windows_build_args: --obfuscate --split-debug-info=debug_info\windows
  logo_path: windows\runner\resources\app_icon.png
