name: anysend
description: AnySend Client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  async: ^2.11.0
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_timer_countdown: ^1.0.5
  flutter_webrtc: ^0.9.45
  http_interceptor: ^1.0.2
  intl: any
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  provider: ^6.0.5
  web_socket_channel: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

import_sorter:
  comments: false
