name: Release MSIX to Microsoft Store

on: workflow_dispatch

# Declare default permissions as read only.
permissions: read-all

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.x'
          channel: 'stable'
      - uses: microsoft/setup-msstore-cli@v1

      # Instructions on obtaining these secrets can be found at https://github.com/marketplace/actions/windows-store-publish#obtaining-your-credentials
      - name: Configure MS CLI
        run: msstore reconfigure --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} --clientId ${{ secrets.AZURE_AD_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_AD_CLIENT_SECRET }} --sellerId ${{ secrets.SELLER_ID }}

      - name: Install dependencies
        run: flutter pub get

      - name: Create MSIX package
        run: msstore package

      - name: Publish MSIX to the Microsoft Store
        run: msstore publish -v
